### ISSUE TITLE
Low performance in WebGL tests.

### ISSUE THREAD

**Issue by EDSln** [IDA-RE-things/Chrome-xp-api-adapter#1]
In tests on https://webglsamples.org for example https://webglsamples.org/aquarium/aquarium.html performance is much lower than the original progwrp.dll The original has 8 fps with 100 fish, yours has 2 fps. The original progwrp.dll loads the processor by 50-75% (8 thread processor), and yours by 12-25%. Win XP SP3, Supermium 122 R4 and latest Thorium.

**Comment by IDA-RE-things** [comment]
Ok. I will check it and will rework.
It was intended for slow/intermediate hardware with 1 or 2 cores.
WebGL was not tested at all.

**Comment by IDA-RE-things** [comment]
fixed (I hope) in new 1.2.0.5029.
Test above now passes same as in original. Have checked it on 4-thread CPU
