### ISSUE TITLE
Crash on page: chrome://system

### ISSUE THREAD

**Issue by SidCos** [IDA-RE-things/Chrome-xp-api-adapter#10]
122.0.6261.152 (R4) XPSP3
v1.2.0.5039, v1.2.0.5041 - Browser crashes on page: chrome://system
There's no error in the log. The window just closes.

v1.2.0.5035 - everything is fine! By the way why this version was removed(renamed)?

**Comment by IDA-RE-things** [comment]
Ok, I have reproduced that crash on chrome://system.

> v1.2.0.5035 - everything is fine! By the way why this version was removed(renamed)?

Because next versions was with additional fixes. Ok, stay with that old, if it works fine for you.

The fix will be available soon.

**Comment by IDA-RE-things** [comment]
see new build 5042.

**Comment by IDA-RE-things** [comment]
Hello, if the bug with that crash (#565) appears only with my replacement, place bugreport here.
But if it appears with both DLL, then its depends on main Chrome.dll, so no need to change this dll's

In any case, crashdump *.dmp will help
