### ISSUE TITLE
5045 last work for WinXPSP3

### ISSUE THREAD

**Issue by z0hm** [IDA-RE-things/Chrome-xp-api-adapter#11]
subj. AcquireSRWLockExclusive don't find.

**Comment by IDA-RE-things** [comment]
Hello, all version runs OK. You just need to rename it properly. Read redme.txt file inside archive, which file to rename.

**Comment by z0hm** [comment]
No, everything is done as it should be

**Comment by IDA-RE-things** [comment]
which version you are trying ?

**Comment by IDA-RE-things** [comment]
This error possible only in one case -- if you renamed other file, but not pointed in readme.

**Comment by IDA-RE-things** [comment]
Ok, I'm closing ticket.
