### ISSUE TITLE
New registry key?

### ISSUE THREAD

**Issue by SidCos** [IDA-RE-things/Chrome-xp-api-adapter#13]
Why in new version 5052 is the **HKLM\Software\Chrome-XPAPI-Adapter** key created in the registry?
It's an empty key without any parameters, and any registry cleaner (like CCleaner) removes it, but it's still a bit unnerving...
Supermium XP

**Comment by IDA-RE-things** [comment]
:) It's a feature to support screensaver prevention. To store var inter-process value of variable.
Original dll also creates this in screensaver-supported version., but with own key.
But while original do it after user pressing "Play" on video, I'm do it just on DLL start (creating this key, if not available).

I can also move creation of this key to "Play", if you dont use video playing. If it makes sense,
current publicly available progwrp dont support this. You should get it from issue topic there to compare.

**Comment by IDA-RE-things** [comment]
The only one thing I can do with it -- also create new key, only when Play pressed. just before data written to registry. So it will not be empty.

**Comment by IDA-RE-things** [comment]
Its will be fixed in next build. Will be changed to create key before using, to store var, instead of on DLL-start phase, So its wiil not be empty, if user not watched video.
The registry var itself is requered for screensaver prevention interprocess approach.

**Comment by IDA-RE-things** [comment]
try build 5053.

**Comment by IDA-RE-things** [comment]
Try another build with same number, uploaded now. There was little bug. The value was incorrect.

**Comment by IDA-RE-things** [comment]
That strange.
Try to delete this wrong key value before using.
I have 0-1 while testing.

**Comment by IDA-RE-things** [comment]
It should not be < 0 in any case.

**Comment by IDA-RE-things** [comment]
UPD: yes the bug with value still here. I will check it more in such case...
Wait for this.

**Comment by IDA-RE-things** [comment]
5054 fixes issue with value.

**Comment by IDA-RE-things** [comment]
Yes, it should be 1, when video playing, and 0 when stopped.

**Comment by IDA-RE-things** [comment]
If you have sceensaver enabled on you system, you can test how this approach works.

**Comment by IDA-RE-things** [comment]
This service started not by DLL's, but by the browser.
bypassing of starting the "WMI Performance Adapter service" it was side effect I think :)
because crashpad was not started,
The crashpad process I think starting this service.
I can try to disable it in future, by patching some DLL call. But its not in priority while. 
But crashpad was restore early , from build 5033.

**Comment by IDA-RE-things** [comment]
I can try to do this when I have time between other tasks, and found where to do it by patching the browser on the fly. I hope its not influents to sandbox ))

**Comment by IDA-RE-things** [comment]
BTW I have not seen any messages frm WMI on My XP system (on both systems). May be I disabled it early.  I mean "Event Viewer"
or what do you mean under the "system log" ?

**Comment by IDA-RE-things** [comment]
I found that `\wbem\wmiprvse.exe` have started with browser start, yes. But where is the messages from it ? My event log is clean.

**Comment by IDA-RE-things** [comment]
Have checked it on both real XP's SP3; on XP SP2 Vm; on Win2k3 Vm -- the event logs are clean.
Note, that on VM's was default system settings.

**Comment by IDA-RE-things** [comment]
Its on XP SP2 VM, after I clenan it and running the browser :

![2](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/assets/9424365/3083abdb-9450-4676-9661-0e041bc7bf79)

![1](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/assets/9424365/92e686b3-b895-4f1d-99f3-f4a4fb4d5855)
