### ISSUE TITLE
A small visual glitch with HW acceleration on XPSP3 (transparent borders are black)

### ISSUE THREAD

**Issue by JoachimHenze** [IDA-RE-things/Chrome-xp-api-adapter#15]
I am using your latest
1.2.0.5059_withHWacceleration_build
against Supermium 122 R6, on XPSP3 x86 with the setting:
`--use-angle=d3d9 --ignore-gpu-blocklist`
GPU: Ati Radeon HD4350

That introduces a small visual glitch around the tab preview, they are being drawn
**Observed result**: "black"
![image](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/assets/33393466/339b14e7-884f-4f26-8114-13318004d5c1)

instead of
**Expected result**: "transparent"

This happens only when I do use the HW acceleration.

Is there a way to fix this, or any specific flag that I could use to turn off the HWaccel for just that specific feature, leaving the rest intact?

![image](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/assets/33393466/522bc8b8-00a3-4158-acf3-b90279e75dbf)

Furthermore: Can I send you a donation of 100$ via Paypal? if yes, please let me know your account.

**Comment by IDA-RE-things** [comment]
yes, I saw it. We should live with it for now. :)
Same bug/issue happens on Win7, I have сhecked it. At least when I use "use-angle=d3d9"
Without any of my changes and with original DLL and Win7 D3DCompiler_47.
So it not depends on this HW acceleration restoration for XP.
I will investigate this issue later. It's anywhere inside libGLESv2.dll,
shaders code etc.
This is not a priority yet, if you agree.

**Comment by JoachimHenze** [comment]
Ok, I am fine with that. I do agree that the `--single-process` issues are more important. I just hoped there would be a flag maybe where I could disable that specific usage of the acceleration in the meantime.
Is it possible to send you 100$ as a thank-you for your recent outstanding work with the acceleration? Paypal?

**Comment by IDA-RE-things** [comment]
Perhaps somewhere its possible to disable the DirectX call for this and do software rendering for that window frame,
but finding this place is still difficult.
And the best thing would be to find out how to correct the correct behavior.
It will be for the future.

The paypal account has problem now for some unknown reason. I have not used it long time. And now I ascertain, whats happened, with their support service.
Thank you for your willing to donate for the work have been done.

**Comment by JoachimHenze** [comment]
I definitely appreciate the current state already. For the record here is the drivers version I am using since ~13years for the GPU:
![image](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/assets/33393466/fdcc9b35-ee98-436d-9b03-58d0caa42700)

**Comment by JoachimHenze** [comment]
Nothing else was claimed, but just to give you a test-update:
The issue does persist in "Supermium 124.0.6367.245 538" x86 + chrome-xpapi-adapter_x86.b5065-wD3D9accel.zip

**Comment by IDA-RE-things** [comment]
Yes, I have already tested it with Supermium v124.
Nothing changed. And we are waiting for this issue will be fixed inside libGLESv2.dll or some other places.
Now its Supermium Issue.

**Comment by JoachimHenze** [comment]
I do confirm that this bug has been fixed to perfection by
https://github.com/win32ss/supermium/releases/tag/v124-r2
The bug is fixed with both: the stock shipped progwrp 1.1.5018 and also with ida-re-things 1.2.0.5067
