### ISSUE TITLE
Tab crash when opening avito.ru.

### ISSUE THREAD

**Issue by EDSln** [IDA-RE-things/Chrome-xp-api-adapter#19]
If I open avito.ru, the page loads at first, but then the tab crashes.
Supermium 124.0.6367.245, chrome-xpapi-adapter_x86.b5066-wD3D9accel, Win XP.
With the original progwrp.dll 1.1.0.0.5018 the site works, the tab does not crash.
![not naming](https://github.com/user-attachments/assets/b67b8869-edd8-458f-bf02-041e916e20cf)

**Comment by IDA-RE-things** [comment]
Yes, its reproduced on my machine. Checking now whats happened.

**Comment by IDA-RE-things** [comment]
Have fixed this issue in new build 5067. The description of issue is in Release notes. If similar breakpoint will happen on some other site, report it also, I will fix it.

**Comment by JoachimHenze** [comment]
I do confirm that the fix does also work for
older "Supermium 122.0.6261.152 (R6) x86" + ida-re-things progwrp.dll 1.2.0.5067
