### ISSUE TITLE
The browser interface language has switched to English.

### ISSUE THREAD

**Issue by EDSln** [IDA-RE-things/Chrome-xp-api-adapter#2]
Chrome automatically switches the interface language depending on the system language, with the original progwrp.dll the language is switched correctly. Win XP SP3, Supermium 122 R4 and latest Thorium.

**Comment by IDA-RE-things** [comment]
It's a feature :). To simplify and minimize size.
It supports interface language in English and other languages,
It can translate pages to another languages.
Just need to set it manually from settings.
I will explain it in "Limitations"

**Comment by EDSln** [comment]
Fix in v1.2.0.5039
