### ISSUE TITLE
Feedback on v1.2.0.5071, no issue.

### ISSUE THREAD

**Issue by rereser** [IDA-RE-things/Chrome-xp-api-adapter#21]
OS: Win XP SP3 with the v1.2.0.5071 release.

Supermium v126 now runs in DirectWrite mode without the need to install the MSVC++ 2015-2019 runtime.
p_advp32.dll, p_ole.dll, pwp_shl.dll can be deleted as the readme.txt says.
When deleting pwrp_k32.dll however, the browser troughs an error on start.
![MWSnap386](https://github.com/user-attachments/assets/15e27331-ec86-43ab-9242-44f8370d282c)
After this one error the browser runs but now in GDI mode.

**Comment by IDA-RE-things** [comment]
I will check, ok, Its strange. On both of my machines it was not appeared.
But I have manually deleted also `d3dcompiler_47.dll` near Chrome.exe
And `pwrp_k32.dll` used only with this 2 libs:  `d3dcompiler_47.dll` and `Dwrite.dll`

you should delete both, and replace them with my D3DCompiler_XP.dll and DWrite.dll from archive.

**Comment by IDA-RE-things** [comment]
> Not having to install the 2015-2019 redist is a big plus and great work.

No, its not touchig Microsoft VC 2015 Redist. It still requered.
Adaptation touches only 4 libs from guy win32ss., which I mentioned.
I proposed my solution instead of his.

**Comment by rereser** [comment]
I dont have the Microsoft VC 2015-2019 Redist installed.
And i don't delete the ucrtbase.dll and api-ms-win-*.dll's.
Your solution works fine, just don't delete the pwrp_k32.dll file.
If you can't reproduce then there is nothing to fix on your end.
Just recommend changing the readme.txt to only delete the p_advp32.dll, p_ole.dll, pwp_shl.dll files.

**Comment by IDA-RE-things** [comment]
But from where it comes? :) That `pwrp_k32` . Its impossible. No links to it inside any files. Just want to know whats happened.

**Comment by rereser** [comment]
Do not kno how i can help, nothing in Crashpad.
The browsertest works fine with DirectWrite.

**Comment by rereser** [comment]
I am no programmer.
I run the browser portable, no install.
![MWSnap389](https://github.com/user-attachments/assets/1dafc8c0-baa2-4ada-b5a9-4253076c47d0)

**Comment by rereser** [comment]
Supermium v126 does create this folder on start if that is of any help.
C:\Documents and Settings\YOUR NAME\Local Settings\Application Data\DWriteCore.

**Comment by rereser** [comment]
A 52 kb FontSet-v3.dat file.
There are no other files installed by supermium on my pc.
Browser is completely portable using the loader.

**Comment by IDA-RE-things** [comment]
Ok, from where you downloaded portable browser? I will also recheck with it, May be it differes somehow. I have used default installer disributive from github. v126-r1.

**Comment by rereser** [comment]
Create the folder structure as in the above screenshots.
Place the extracted supermium files in the correct folder.
Use this ini as a start.
----------------------------------------
[Setup]
AppName=chrome

[FileToRun]
PathToExe=.\Application\$AppName$.exe
Parameters=--user-data-dir="%Profile%" --disable-encryption --disable-machine-id --disable-logging --disable-component-update --disable-background-networking --ignore-certificate-errors

[Environment]
Profile=.\User Data

[Options]
DeleteTemp=true
ShowSplash=false
WriteLog=false
ShowTrayTip=false
-----------------------------------

**Comment by rereser** [comment]
No DWrite.dll besides in the supermium/application folder, same for pwrp_k32.
Will leave it at that as you can not reproduce.
Maybe someone else will post if they have this error.

Another issue presented itself just now.
Latest supermium release (today) is now slower to launch with your files.

**Comment by IDA-RE-things** [comment]
> Latest supermium release (today) is now slower to launch with your files.

Will check why its happenes, ok. Have not seen while this one :)

**Comment by IDA-RE-things** [comment]
Hmm, I have checked and found that in today release v126-**r2** there are reference to `pwrp_k32`  from `ucrtbase.dll`.
So may be you have runned this before with that version, but not v126-**r1** ? . And result was "pwrp_k32 missing"

**Comment by rereser** [comment]
During this conversation i was running v126-R1.
I did the update to v126-R2 just now.

**Comment by IDA-RE-things** [comment]
have uploaded new build 5072 for Sm v126-r2.
Should not be slower, because uses less number of libs at least.

**Comment by rereser** [comment]
Build 5072 works fine.
No slow load, no errors after removing files as described in the readme.txt.
Thank you.
