### ISSUE TITLE
STATUS_BREAKPOINT on Chrome webstore.

### ISSUE THREAD

**Issue by rereser** [IDA-RE-things/Chrome-xp-api-adapter#22]
Supermium 126.0.6478.249 R3 (XP x64 Hotfix) with v1.2.0.5073
OS: Windows XP SP3.
Visit the chromewebstore.
Select an extension that has reviews, select "See all reviews" and scroll down.
It will go "AW Snap" with STATUS_BREAKPOINT message.
Does not happen with the original progwrp.dll and the other dll's.
Example link: https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm/reviews
v1.2.0.5072 works fine so this is a regression in v1.2.0.5073
Tested in clean profile.

**Comment by IDA-RE-things** [comment]
Have checked. One of the stub-functions was called after implementing removing dependency on excluded dll's. (r5072 vs r5073)
Its normal situation that it can happen somewhere on some site (But I have not seen it in my everyday browsing experience earlier).  
Have reproduced your case. And now have fixed this.
Now all works fine again.
r5073-fix

**Comment by rereser** [comment]
Can confirm fix, thank you.
