### ISSUE TITLE
Google Play: problems with displaying "Google Material Icons"

### ISSUE THREAD

**Issue by xixhub** [IDA-RE-things/Chrome-xp-api-adapter#25]
WinXP SP3
Supermium 124.0.6367.245 R2 with <ins>v1.2.0.5073</ins>
Supermium 126.0.6478.254 R4 with <ins>v1.2.0.5078</ins>
I get a problem on Google Play with missing icons (font). No such problem on the standard DWrite.dll.
example link https://play.google.com/store/apps/details?id=app.organicmaps

![ERROR](https://github.com/user-attachments/assets/8d8d80b0-d977-4883-b25d-18fef1b6d968)
![OK1](https://github.com/user-attachments/assets/8a62eef8-84c6-4b34-a291-e199be541d65)
![OK2](https://github.com/user-attachments/assets/657159de-168b-4d76-a0f8-e341966e8404)

**Comment by IDA-RE-things** [comment]
Okay, I will check why it is. (lo priority). Its not so simple to detect cause, only by excluding changes one by one..
May be its a side effect of my cutting-down of dll's around.
On another sites I have not seen this problem while, so I will not do anythig while.
In this case you can stay use standard DWrite if this does matter for your.

**Comment by xixhub** [comment]
Yeah, well, take your time!
This is also so far the only site for me where I've noticed such a problem. Other than that, everything else is working fine.

**Comment by xixhub** [comment]
hmmm, apparently Google fixed the problem themselves: everything is now displaying normally (v1.2.0.5073 & v1.2.0.5078).

**Comment by IDA-RE-things** [comment]
Good. Will close the issue in this case.
