### ISSUE TITLE
The x32 browser does not run in XP x64.

### ISSUE THREAD

**Issue by EDSln** [IDA-RE-things/Chrome-xp-api-adapter#4]
After launching, the process starts for a second, then terminates. No errors are displayed. The following lines appear in the log:

[0506/143352.156:ERROR:registration_protocol_win.cc(136)] TransactNamedPipe: The channel was closed. (0x6D)
[0506/143352.156:ERROR:crashpad_client_win.cc(144)] crash server failed to launch, self-terminating

v1.2.0.5029

Too late to see that the readme says that. Well, let it be an issue, so that there is something to close. :)

**Comment by IDA-RE-things** [comment]
Ok :).  I haven't tested it on Wow64, only x86. It was also not intended for such launch. So it's expected :).
Ok. I'll check and fix it.

**Comment by EDSln** [comment]
Fixed in v1.2.0.5031
