### ISSUE TITLE
Where can I find the DLL? 

### ISSUE THREAD

**Issue by GmaerSoft42** [IDA-RE-things/Chrome-xp-api-adapter#6]
Ok, maybe it's somewhere and I haven't looked deep enough, but some guy names "rereser" on MSFN managed to download it 7 hrs ago, so has it been closed-source before or something has happened? Source code is only the README.

I know this DLL is closed source until original will be opensource, but has this been made only 1 hour ago?

Time of writing : 20:55 GMT @ 09/05/2024

![image](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/assets/162634737/8fb94d71-82de-409c-b13c-abbe06ee7a26)

**Comment by IDA-RE-things** [comment]
It will be available soon with next improvement.

**Comment by GmaerSoft42** [comment]
So a v1.3 will be available and will perform better than the 1.2?

**Comment by IDA-RE-things** [comment]
no, still v.1.2, but another build. Check it tomorrow (I think) in same place.

**Comment by GmaerSoft42** [comment]
Today is tomorrow, and still nothing in the releases section. It's only 8:40 AM so I'll wait

**Comment by IDA-RE-things** [comment]
I can enable it again. Buit this was detected some problem. May be it will not be reproduced.
k. you also will test this.

**Comment by IDA-RE-things** [comment]
Enabled.

**Comment by GmaerSoft42** [comment]
Alright. Thank you. I'll mark this issue as closed.
