### ISSUE TITLE
Can't acess any website

### ISSUE THREAD

**Issue by Gonimbrasia** [IDA-RE-things/Chrome-xp-api-adapter#8]
Using both Supermium and Thorium with either of the current releases causes the browser to close as soon as a site starts to load. It happens with any website and there is no error message or log created. Trying to acess the likes of Settings or Extensions causes the tab to crash with Error code: STATUS_ACCESS_VIOLATION. Other than that, the browsers certainly launch more quickly.
There are no such problems using the original progwrp.dll.

Windows XP Home Edition Version 2002 Service Pack 3
Pentium 4 CPU 3.00GHz
2.00 GB of RAM

**Comment by IDA-RE-things** [comment]
Ok. Thats strange. Can you place here crashdump (*.dmp) ?
You can find it in  `\Supermium_UserData\Crashpad\reports\` 
(clear this directory before run of the browser to prevent confusion)

**Comment by IDA-RE-things** [comment]
Its may be bacause of `Home Edition` of XP. I'm testing it on Professional only. 
But may be something another. I need a crashdump to check.

**Comment by Gonimbrasia** [comment]
Here's a crashdump. Hope it helps.
[26724685-097e-4c05-a2dc-93ea32274bdd.dmp](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/files/15283988/26724685-097e-4c05-a2dc-93ea32274bdd.dmp)

**Comment by IDA-RE-things** [comment]
Ok. will check now.

**Comment by IDA-RE-things** [comment]
The problem is in handling of specific info for CPU. (though on all of my machines its not reproduced)
I think the fix will be available tomorrow.

**Comment by Gonimbrasia** [comment]
Ok, thanks. I'll wait and see what you come up with tomorrow.

**Comment by IDA-RE-things** [comment]
see new build 5042. I think it fixed. But you should check.

**Comment by Gonimbrasia** [comment]
Sorry but it's still happening. I've noticed that it creates two crashdump files each time, so this time I've attached both.
[b49447a3-1a4c-415d-806f-b2b7e19bbd35.dmp](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/files/15284370/b49447a3-1a4c-415d-806f-b2b7e19bbd35.dmp)
[8c7ee13a-94ea-4f84-b0dd-46ff204ad7ec.dmp](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/files/15284371/8c7ee13a-94ea-4f84-b0dd-46ff204ad7ec.dmp)

**Comment by IDA-RE-things** [comment]
Have seen. Yes, same problem still here.
Will do something more.. 
So, it just Pentium 4. Hyperthreading enabled ?

**Comment by Gonimbrasia** [comment]
> Have seen. Yes, same problem still here. Will do something more.. So, it just Pentium 4. Hyperthreading enabled ?

Yes, that's correct.

**Comment by IDA-RE-things** [comment]
Try another fix. build 5044.

**Comment by Gonimbrasia** [comment]
> Try another fix. build 5044.

Works perfectly. Thank you so much. It's a huge improvement over the original progwrp.dll for me.
